### ISSUE TITLE
subprocess.CalledProcessError: Command 'yarn run production --apps ury_pos --run-build-command' returned non-zero exit status 1. ERROR: bench build --app ury_pos subprocess.CalledProcessError: Command 'bench build --app ury_pos' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Osalama1** [ury-erp/pos#1]
i installed ury and it's okay
i tried to get ury_po with this command `bench get-app ury_pos https://github.com/ury-erp/pos.git`
i got this error

`subprocess.CalledProcessError: Command 'yarn run production --apps ury_pos --run-build-command' returned non-zero exit status 1.
ERROR: bench build --app ury_pos
subprocess.CalledProcessError: Command 'bench build --app ury_pos' returned non-zero exit status 1.`

ERPNext: v14.47.4
Frappe Framework: v14.54.1

**Comment by Sanjusha-tridz** [comment]
Hi,

The error will not affect the functionality of "URY pos" ,it is a result of dependencies of "Doppio".
To resolve this, you can try installing the "doppio" app in your Bench environment. Use the following command:

```
bench get-app https://github.com/NagariaHussain/doppio

```

Installing "doppio" may provide the necessary dependencies or configurations required for the successful build of the "ury_pos" app. After installing "doppio," attempt to install "ury_pos" again using the original command

```
bench get-app ury_pos https://github.com/ury-erp/pos.git

```
