### ISSUE TITLE
Could not resolve "../../../doppio/libs/resourceManager" from "src/main.js"

### ISSUE THREAD

**Issue by Islammoustafa95** [ury-erp/pos#2]
Bench build or / npm install & yarn build fails with this error 

`Could not resolve "../../../doppio/libs/resourceManager" from "src/main.js"`

`Run `npm audit` for details.
$ vite build --base=/assets/ury_pos/urypos/ && yarn copy-html-entry
vite v4.5.2 building for production...
✓ 9 modules transformed.
✓ built in 201ms
Could not resolve "../../../doppio/libs/resourceManager" from "src/main.js"
file: /home/frappe/frappe-bench/apps/ury_pos/urypos/src/main.js
error during build:
RollupError: Could not resolve "../../../doppio/libs/resourceManager" from "src/main.js"
    at error (file:///home/frappe/frappe-bench/apps/ury_pos/urypos/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.handleInvalidResolvedId (file:///home/frappe/frappe-bench/apps/ury_pos/urypos/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)
    at file:///home/frappe/frappe-bench/apps/ury_pos/urypos/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

happening also in ury_pos app and ury_mosaic app

Ubuntu 22.04 lts
frappe v14
erpnext v14

cannot open the pos of URY and also cannot open Mosaic

**Comment by Sanjusha-tridz** [comment]
Hi,

The error will not affect the functionality of "URY POS" or "URY Mosaic" ,it is a result of dependencies of "Doppio".
To resolve this, you can try installing the "doppio" app in your Bench environment. Use the following command:

```
bench get-app https://github.com/NagariaHussain/doppio

```
Installing "doppio" may provide the necessary dependencies or configurations required for the successful build of the "ury_pos" app. After installing "doppio," attempt to install "URY POS" and "URY Mosaic" again using the command

```
bench get-app https://github.com/ury-erp/pos.git

```


```
bench get-app https://github.com/ury-erp/mosaic.git

```
