### ISSUE TITLE
Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by Helkyd** [ury-erp/pos#3]
When trying to login on shows below error 
**Cannot read properties of undefined (reading 'data')**

How to solve this so i can login ?
If using normal login it works only when trying POS

Installed apps 

![image](https://github.com/ury-erp/pos/assets/20396898/712869ca-0039-4d38-858e-d9f066da0bc9)

**Comment by Helkyd** [comment]
![image](https://github.com/ury-erp/pos/assets/20396898/03b9e9d5-2982-4f6c-a3b4-1454ddd4cb9a)


This is what i get from the Console.

**Comment by Sanjusha-tridz** [comment]
Resolved : **"Cannot read properties of undefined (reading 'data')"** (3221c18d5ae5c451046dc6fe49793d0bffede64f)
